/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface NibpComponent {
    'Vitals': any;
    'first': string;
    'last': string;
    'middle': string;
    'rest': string;
  }
  interface NibpComponentAttributes extends StencilHTMLAttributes {
    'Vitals'?: any;
    'first'?: string;
    'last'?: string;
    'middle'?: string;
    'rest'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'NibpComponent': Components.NibpComponent;
  }

  interface StencilIntrinsicElements {
    'nibp-component': Components.NibpComponentAttributes;
  }


  interface HTMLNibpComponentElement extends Components.NibpComponent, HTMLStencilElement {}
  var HTMLNibpComponentElement: {
    prototype: HTMLNibpComponentElement;
    new (): HTMLNibpComponentElement;
  };

  interface HTMLElementTagNameMap {
    'nibp-component': HTMLNibpComponentElement
  }

  interface ElementTagNameMap {
    'nibp-component': HTMLNibpComponentElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
