/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface TemperatureComponent {
    'Vitals': any;
    'first': string;
    'last': string;
    'middle': string;
    'rest': string;
  }
  interface TemperatureComponentAttributes extends StencilHTMLAttributes {
    'Vitals'?: any;
    'first'?: string;
    'last'?: string;
    'middle'?: string;
    'rest'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'TemperatureComponent': Components.TemperatureComponent;
  }

  interface StencilIntrinsicElements {
    'temperature-component': Components.TemperatureComponentAttributes;
  }


  interface HTMLTemperatureComponentElement extends Components.TemperatureComponent, HTMLStencilElement {}
  var HTMLTemperatureComponentElement: {
    prototype: HTMLTemperatureComponentElement;
    new (): HTMLTemperatureComponentElement;
  };

  interface HTMLElementTagNameMap {
    'temperature-component': HTMLTemperatureComponentElement
  }

  interface ElementTagNameMap {
    'temperature-component': HTMLTemperatureComponentElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
