/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface IbpComponent {
    'Vitals': any;
    'first': string;
    'last': string;
    'middle': string;
    'rest': string;
  }
  interface IbpComponentAttributes extends StencilHTMLAttributes {
    'Vitals'?: any;
    'first'?: string;
    'last'?: string;
    'middle'?: string;
    'rest'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'IbpComponent': Components.IbpComponent;
  }

  interface StencilIntrinsicElements {
    'ibp-component': Components.IbpComponentAttributes;
  }


  interface HTMLIbpComponentElement extends Components.IbpComponent, HTMLStencilElement {}
  var HTMLIbpComponentElement: {
    prototype: HTMLIbpComponentElement;
    new (): HTMLIbpComponentElement;
  };

  interface HTMLElementTagNameMap {
    'ibp-component': HTMLIbpComponentElement
  }

  interface ElementTagNameMap {
    'ibp-component': HTMLIbpComponentElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
