/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface MyComponent {
    'Persons': any;
    'first': string;
    'last': string;
    'middle': string;
  }
  interface MyComponentAttributes extends StencilHTMLAttributes {
    'Persons'?: any;
    'first'?: string;
    'last'?: string;
    'middle'?: string;
  }

  interface TempCard {
    'Vitals': any;
    'chnageArray': (array: any) => void;
    'first': string;
    'last': string;
    'middle': string;
  }
  interface TempCardAttributes extends StencilHTMLAttributes {
    'Vitals'?: any;
    'first'?: string;
    'last'?: string;
    'middle'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'MyComponent': Components.MyComponent;
    'TempCard': Components.TempCard;
  }

  interface StencilIntrinsicElements {
    'my-component': Components.MyComponentAttributes;
    'temp-card': Components.TempCardAttributes;
  }


  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLTempCardElement extends Components.TempCard, HTMLStencilElement {}
  var HTMLTempCardElement: {
    prototype: HTMLTempCardElement;
    new (): HTMLTempCardElement;
  };

  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement
    'temp-card': HTMLTempCardElement
  }

  interface ElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'temp-card': HTMLTempCardElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
